version: '3.9'
services:

  # PHP-FPM container
  matyar_php:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    container_name: matyar_php
    networks:
      - app_network

  # Nginx container
  matyar_nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: matyar_nginx
    depends_on:
      - matyar_php
    networks:
      - app_network
      - alphax_network
    labels: 
      - "nginx.host=matyar.alphaxsoft.com" 
      - "nginx.port=80"
    expose:
      - "80"

  # Database
  db:
    image: mysql:8.0
    container_name: matyar_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app_network
    # --- برای سرور با منابع محدود، این بخش را اضافه کنید ---
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 700M

  # ----------------- بخش اضافه شده برای Meilisearch -----------------
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: matyar_meilisearch
    restart: unless-stopped
    environment:
      # کلید اصلی را از فایل .env بخوان
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
    volumes:
      # از این والیوم برای ذخیره دائمی داده‌های Meilisearch استفاده می‌شود
      - meili-data:/data.ms
    networks:
      - app_network
    # --- برای سرور با منابع محدود، این بخش را اضافه کنید ---
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 800M
  # ----------------- پایان بخش اضافه شده -----------------

volumes:
  db-data:
  meili-data: # <-- والیوم جدید برای Meilisearch

networks:
  app_network:
    driver: bridge
  alphax_network:
    name: alphax_network
    external: true