version: '3.9'
services:

  # PHP-FPM container
  matyar_php:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    container_name: matyar_php
    networks:
      - app_network
    ### ADD THIS SECTION ###
    # This makes the project files available inside the container.
    volumes:
      - .:/var/www/html

  # Nginx container
  matyar_nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: matyar_nginx
    depends_on:
      - matyar_php
    networks:
      - app_network
      - alphax_network
    labels: 
      - "nginx.host=matyar.alphaxsoft.com" 
      - "nginx.port=80"
    expose:
      - "80"
    ### ADD THIS SECTION ###
    # This makes Nginx see the exact same files as the PHP container.
    # THIS IS THE FIX FOR THE CSS (MIME type) ERROR.
    volumes:
      - .:/var/www/html

  # Database (no changes needed here)
  db:
    image: mysql:8.0
    container_name: matyar_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 700M

  # Meilisearch (no changes needed here)
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: matyar_meilisearch
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=topsecret1400
    volumes:
      - meili-data:/data.ms
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 800M

volumes:
  db-data:
  meili-data:

networks:
  app_network:
    driver: bridge
  alphax_network:
    name: alphax_network
    external: true