services:
  # The Application's Web Server (Nginx)
  app:
    image: nginx:1.25-alpine
    container_name: matyar
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9001:80" # For local testing, not strictly needed for proxy
    environment:
      # IMPORTANT: These variables are read by docker-gen
      - VIRTUAL_HOST=matyar.alphaxsoft.com # Change to your desired subdomain
      - VIRTUAL_PORT=80
    depends_on:
      - php
      - db
    networks:
      - default
      - core_network # Connect to the reverse proxy network

  # PHP-FPM Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: matyar_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - default

  # Database Service (MySQL)
  db:
    image: mysql:8.0
    container_name: matyar_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Use a secure root password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - default

  # Queue Worker (Optional)
  worker:
    image: matayr_php # Reuse the PHP image we built
    container_name: matayr_worker
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
      - db
    networks:
      - default

volumes:
  db-data:
    driver: local

networks:
  default:
    driver: bridge
  core_network:
    external: true
    name: infra_network # IMPORTANT: Use the actual name of your core network