services:
  # The Application's Web Server (Nginx)
  app:
    image: nginx:1.25-alpine
    container_name: matyar
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9001:80"
    # ❌ REMOVED environment variables for docker-gen
    # ✅ ADDED labels that match your nginx.tmpl
    labels:
      - "nginx.host=matyar.alphaxsoft.com"
      - "nginx.port=80"
    depends_on:
      - php
      - db
    networks:
      - default
      - alphax_network

  # PHP-FPM Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: matyar-app:latest
    container_name: matyar_php
    restart: unless-stopped
    networks:
      - default

  # Database Service (MySQL)
  db:
    image: mysql:8.0
    container_name: matyar_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - default

  # Queue Worker (Optional)
  worker:
    image: matyar-app:latest
    container_name: matyar_worker
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3
    depends_on:
      - php
      - db
    networks:
      - default

volumes:
  db-data:
    driver: local

networks:
  default:
    driver: bridge
  alphax_network:
    external: true
    name: alphax_network